<div class="header">The Humans: A History</div><br><div style="align: justify;">By 2008 the Human Genome Project had been completed.  Soon there after the human race began using this biological knowledge for good; in use in medicine, sadly not much later and this knowledge was also exploited for darker purposes.  Acts of terrorism were committed in which forms of biological warfare were adopted that used knowledge of the human genome to target specific races to devastating consequences.  A UN treaty was called in 2018 that banned the use of any technology that involved knowledge of the human genome be it good or bad.  Books, journals and research on the human genome were all destroyed and this branch of science soon became extinct but for a few scientologist cults and groups of scientists that still kept and taught the information, and to a small level attempted to research into it further.<br>
<br>
Sometime towards the second half of the 21st century energy resources became very limited.  Humans had begun moving to a hydrogen economy but this was still in its infancy and was unable to provide adequate levels of energy for the ever-increasing energy demand of planet earth.  Around the same time humans had discovered new concepts and theories into propulsion, which they felt could pave the way to mass space travel.  The combination of the increasing population coupled with the lack of resources forced humans to acquire new habitats in space.  Space travel progressed extremely rapidly, and by the early 22nd century humans had spread far beyond their own solar system.  <br>
<br>
This rapid acquisition of new and valuable lands for humans echoed memories of the American Gold Rush (a much earlier historical moment in humankinds development).  The rapid increase in territory for humans brought with it a lack of available law enforcement as well as a lack of sociological structure.  This in turn led to a dark moment in human kinds history whereby people fought desperately to acquire new territory in order to gain power.  Soon small groups of people fighting for land led to gang like structures forming.  Eventually by around 2250 “the Gang Wars” had ended, and two main empires had evolved.  One of these empires was known to the other as “cloners” due to their dependence on cloning from earlier scientific information on the human genome project still passed on through cults and a few scientists.<br>
<br>
These two empires had formed de-localised territories in space that had learnt to coexist through a number of agreed treaties.  However this chapter of peace in humankinds history was very soon disturbed when in 2264 the first attack from a number of unknown organisms was recorded.  This pattern soon continued and an intergalactic war broke out between humans and the recently discovered alien life form.  <br>
<br>
The human empire known as “cloners” used overwhelming numbers of clones to defend itself against the aliens, this allowed for a successful defense but put little value on human life.  The other empire incurred such demoralizing loses that it turned to developing radical new technologies to defend itself.  One area of defense that it turned to was machinery.  They developed machinery that used highly sophisticated artificial intelligence programming for their own protection.  This however brought with it serious consequences.  Eventually in 2286 this sophisticated machinery that had played an effective role in the humans protection against aliens somehow turned on its human creators.  <br>
<br>
Now in 2306 humankind faces an uncertain future, they must stand and fight it out against aliens, machinery and even themselves in this aggressive new world.</div>
